# Generated by Django 5.0.4 on 2024-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contemporaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famousperson',
            name='hpi',
            field=models.FloatField(db_index=True),
        ),
    ]
